download_url: https://galaxy.ansible.com/download/community-general-6.3.0.tar.gz
format_version: 1.0.0
name: general
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 6.3.0
version_url: https://galaxy.ansible.com/api/v2/collections/community/general/versions/6.3.0/
