---
- name: "write information into awx api job dict"
  tags:
    - always

  block:
    - name: "set fact for job dict"
      ansible.builtin.set_fact:
        dict_return_to_job_artifacts: "{{ default_job_artifacts }}"  

    - name: "set special stat"
      ansible.builtin.set_stats:
        data:
          job_data: "{{ dict_return_to_job_artifacts |default( 'empty' ) }}"
          aggregate: false
          per_host: false

  rescue:
    - name: "error writing into awx api job dict"
      ansible.builtin.fail:
        msg: "error writing job dict"

