###############################################
# rolename: r_update_all
#
# function:
# - update linux operating system in a depending matter
#
# dev:  {{ cookiecutter.developer }}
# mail: {{ cookiecutter.developer_mail }}
#
# rel:  {{ cookiecutter.release }}
#
# ref:
# - ../defaults/*
#
# changelog:
# -
##############################################
---
# tasks file for r_update_all
- name: "update linux os"
  tags:
    - update_all

  block:
    - name: "update all packages"
      ansible.builtin.dnf:
        name: "*"
        state: latest

  rescue:
    - name: "role {{ ansible_role_name }} failed"
      ansible.builtin.fail:
        msg: "error: during update linux os"
