---
# https://github.com/pre-commit
#
repos:
- repo: https://github.com/ansible/ansible-lint.git
  rev: v6.1.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

- repo: local
  hooks:
  - id: sphinx
    name: Build documentation with Sphinx
    language: system
    entry: python3 -m sphinx -b html . _html
    verbose: true
    # do not match any file -- always run exactly once
    files: ^$
    always_run: true
    pass_filenames: false
