---
- name: "run fast for notification {{ ansible_play_hosts|to_yaml }}"
  hosts: "{{ group_name | default('mn1') }}"
  collections:
    - community.general
  gather_facts: false
  any_errors_fatal: true
  ignore_unreachable: false
  debugger: on_failed
  become: true
  vars:
    pl_name: "p_fast.yml"

  tasks:
    - block:
        - name: "debug"
          ansible.builtin.debug:
            msg: "{{ pl_name }}"

        - name: "set fact for state"
          ansible.builtin.set_fact:
            dict_results: "{'varName': '','varValue': ''}"
            dict_messages: "{'type': '', 'action': '', 'message': ''}"
            dict_overallStatus: "{'status': '','message': ''}"

        - name: "set special stat"
          ansible.builtin.set_stats:
            data:
              results: "{{ dict_results |default({'state1':'empty', 'state2':'empty'}) }}"
              messages: "{{ dict_meaasge |default('empty') }}"
              overallStatus: "{'status': 'status','message': 'message'}"
            aggregate: false
            per_host: false

      rescue:
        - name: "pre tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"
