---
- name: "run fast for notification {{ ansible_play_hosts|to_yaml }}"
  hosts: "{{ group_name | default('all') }}"
  collections:
    - community.general
  gather_facts: false
  any_errors_fatal: true
  ignore_unreachable: false
  debugger: on_failed
  become: true
  vars:
    pl_name: "p_fast.yml"

  tasks:
    - block:
        - name: "debug"
          ansible.builtin.debug:
            msg: "{{ pl_name }}"

        - name: "set fact for state"
          ansible.builtin.set_fact:
            dict_return_to_inubit: {
                        'key1': 'val1', 
                        'key2': 'val2' 
                        }   

        - name: "set special stat"
          ansible.builtin.set_stats:
            data:
              value1: "{{ dict_return_to_inubit |default({'key1':'empty', 'key1':'empty'}) }}"
              value2: "{{ scalar_return_to_inubit |default('empty') }}"
            aggregate: false
            per_host: false
