---
- name: "run fast for notification {{ ansible_play_hosts|to_yaml }}"
  hosts: "{{ group_name | default('all') }}"
  collections:
    - community.general
    - linux.common
    - linux.bootstrap_ansible_user
    - linux.update
  gather_facts: false
  any_errors_fatal: true
  ignore_unreachable: false
  debugger: on_failed
  become: true
  vars:
    pl_name: "p_fast.yml"

  tasks:
    - block:
        - name: "debug"
          ansible.builtin.debug:
            msg: "{{ pl_name }}"

        - name: "set fact for state"
          ansible.builtin.set_fact:
            state_dict: {
                        'Name': 'John Doe', 
                        'Email': 'john.doe@gisa.de' 
                        }   

#        - name: "set special stat"
#          ansible.builtin.set_stats:
#            data:
#              value: "{{ state_dict }}"
#            aggregate: false
#            per_host: false
