---
# tasks file for r_set_state
- name: "run fast for notification {{ ansible_play_hosts|to_yaml }}"
  tags:
    - set_state


  block:
    - name: "set fact" 
      ansible.builtin.set_fact:
        results: "{{ dict_results |default({}) }}"
        messages: "{{ dict_messages |default({}) }}"
        overallStatus: "{{ dict_overallStatus |default({}) }}"

    - name: "set special stat"
      ansible.builtin.set_stats:
        data:
          results: "{{ results }}"
          messages: "{{ messages }}"
          overallStatus: "{{ overallStatus }}"
        aggregate: "{{ bool_aggregate }}"
        per_host: "{{ bool_per_host }}"

    - name: "pause"
      ansible.builtin.pause:
        seconds: 2

  rescue:
    - name: "error setting sepial fact"
      ansible.builtin.fail:
        msg: "error setting sepial fact"
