---
# tasks file for r_set_state
- name: "set state for job endpoint"
  tags:
    - set_state

  block:
    - name: "set fact" 
      ansible.builtin.set_fact:
        results: "{{ dict_results |default({}) }}"
        messages: "{{ dict_messages |default({}) }}"
        overallStatus: "{{ dict_overallStatus |default({}) }}"

    - name: "set special state"
      ansible.builtin.set_stats:
        data:
          results: "{{ results }}"
          messages: "{{ messages }}"
          overallStatus: "{{ overallStatus }}"
        aggregate: "{{ bool_aggregate }}"
        per_host: "{{ bool_per_host }}"
