---
- name: "run fast for notification {{ ansible_play_hosts|to_yaml }}"
  hosts: "{{ group_name | default('mn1') }}"
  gather_facts: false
  any_errors_fatal: true
  ignore_unreachable: false
  debugger: on_failed
  become: true
  vars:
    pl_name: "p_fast.yml"

##############################################

  pre_tasks:
    - block:
        - name: "set special stat"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            dict_results: {'varName': 'pre_tasks', 'varValue': 'pre_tasks'}
            dict_messages: {'type': 'pre_tasks', 'action': 'pre_tasks', 'message': 'pre_tasks'}
            overallStatus: {'status': 'pre_tasks', 'message': 'pre_tasks'}

      rescue:
        - name: "pre tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"

      tags:
        - always

##############################################

  tasks:
    - block:
        - name: "set special stat"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            results: "{{ dict_results |default({}) }}"
            messages: "{{ dict_messages |default({}) }}"
            overallStatus: "{{ dict_overallStatus |default({}) }}"
          tags:
            - set_state

      rescue:
        - name: "pre tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"

##############################################

  post_tasks:
    - block:
        - name: "set special stat"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            results: "{{ dict_results |default({}) }}"
            messages: "{{ dict_messages |default({}) }}"
            overallStatus: "{{ dict_overallStatus |default({}) }}"

      rescue:
        - name: "pre tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"

      tags:
        - always

##############################################
