---
- name: "run fast for notification {{ ansible_play_hosts|to_yaml }}"
  hosts: "{{ group_name | default('mn1') }}"
  gather_facts: true
  any_errors_fatal: true
  ignore_unreachable: false
  debugger: never
  become: true
  vars:
    pl_name: "p_fast.yml"
    error: "{{ error|default('0') }}"

##############################################

  pre_tasks:
    - block:
        - name: "build error"
          ansible.builtin.fail:
            msg: "{{ error }}"
          failed_when: error == "1"

      rescue:
        - name: "set fail state"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            dict_results: {'varName': 'pre_tasks failed', 'varValue': 'pre_tasks failed'}
            dict_messages: {'type': 'pre_tasks failed', 'action': 'pre_tasks failed', 'message': 'pre_tasks failed'}
            dict_overallStatus: {'status': 'pre_tasks failed', 'message': 'pre_tasks failed'}

        - name: "pre tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"
  
      tags:
        - always

##############################################

  tasks:
    - block:
        - name: "build error"
          ansible.builtin.fail:
            msg: "{{ error }}"
          failed_when: error == "2"

      rescue:
        - name: "set fail state"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            dict_results: {'varName': 'tasks failed', 'varValue': 'tasks failed'}
            dict_messages: {'type': 'tasks failed', 'action': 'tasks failed', 'message': 'tasks failed'}
            dict_overallStatus: {'status': 'tasks failed', 'message': 'tasks failed'}

        - name: "tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"

##############################################

  post_tasks:
    - block:
        - name: "build error"
          ansible.builtin.fail:
            msg: "{{ error }}"
          failed_when: error == "3"

        - name: "set special stat"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            dict_results: {'varName': 'success', 'varValue': 'success'}
            dict_messages: {'type': 'success', 'action': 'success', 'message': 'success'}
            dict_overallStatus: {'status': 'success', 'message': 'success'}

      rescue:
        - name: "set fail state"
          ansible.builtin.include_role:
            name: r_set_state
          vars:
            dict_results: {'varName': 'post_tasks failed', 'varValue': 'post_tasks failed'}
            dict_messages: {'type': 'post_tasks failed', 'action': 'post_tasks failed', 'message': 'post_tasks failed'}
            dict_overallStatus: {'status': 'post_tasks failed', 'message': 'post_tasks failed'}

        - name: "post tasks {{ pl_name }} failed"
          ansible.builtin.fail:
            msg: "running rollback"

      tags:
        - always

##############################################
