###############################################
# rolename: r_reboot_nodes
#
# function:
# - reboot given nodes and wait for startup in async way
#
# dev:  {{ cookiecutter.developer }}
# mail: {{ cookiecutter.developer_mail }}
#
# rel:  {{ cookiecutter.release }}
#
# ref:
# - ../defaults/*
#
# changelog:
# -
##############################################
---
# tasks file for r_reboot_nodes
- name: "reboot given nodes"
  tags:
    - reboot_nodes

  block:
    - name: "initiating reboot of managed nodes"
      ansible.builtin.shell: |
              /bin/sleep ${reboot_sleep_timer} &&  shutdown -r now "ansible reboot triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: "wait for startup"
      ansible.builtin.wait_for_connection:
        delay: "{{ wait_for_connection_delay }}"

  rescue:
    - name: "role {{ ansible_role_name }} failed"
      ansible.builtin.fail:
        msg: "error: during reboot given nodes"
